$terminal = uwsm app -- kitty
$browser = uwsm app -- zen-browser
$menu = hyprlauncher


bind = ALT, Q, exec, $terminal
bind = ALT, B, exec, $browser
bind = ALT, C, killactive,
bind = ALT, L, exit,
bind = ALT, E, exec, uwsm app -- dolphin --new-window
bind = ALT, V, togglefloating,
bind = Alt, Tab, exec, ~/.config/hypr/scripts/alt-tab.sh
bind = ALT, F, fullscreen, 1
bind = ALT, R, exec, $menu
bindm=ALT,mouse:272,movewindow
bindm=ALT,mouse:273,resizewindow
bind = , PRINT, exec, hyprshot -m region


# Volume and Media Control
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMicMute, exec, pamixer --default-source -m
bind = , XF86AudioMute, exec, pamixer -t
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
