wallpaper {
    monitor = HDMI-A-1
    path = /home/gabriel/Imagens/hhma415rpztb1.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = /home/gabriel/Imagens/yhXNepW.png
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = /home/gabriel/Imagens/HUYnMEB.jpeg
    fit_mode = cover
}
